/*
 * File: app/store/Combo/BusinessTypeStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RiskManagement.store.Combo.BusinessTypeStore', {
    extend: 'Ext.data.Store',
    alias: 'store.businesstypestore',

    requires: [
        'RiskManagement.model.Combo.BusinessTypeModel',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Combo.BusinessTypeStore',
            model: 'RiskManagement.model.Combo.BusinessTypeModel',
            data: [
                {
                    id: 784,
                    Name: 'voluptatum'
                },
                {
                    id: 874,
                    Name: 'eos'
                },
                {
                    id: 268,
                    Name: 'officiis'
                },
                {
                    id: 610,
                    Name: 'pariatur'
                },
                {
                    id: 528,
                    Name: 'ipsa'
                },
                {
                    id: 208,
                    Name: 'eum'
                },
                {
                    id: 952,
                    Name: 'fugiat'
                },
                {
                    id: 542,
                    Name: 'minima'
                },
                {
                    id: 233,
                    Name: 'ut'
                },
                {
                    id: 948,
                    Name: 'explicabo'
                },
                {
                    id: 147,
                    Name: 'ipsa'
                },
                {
                    id: 710,
                    Name: 'et'
                },
                {
                    id: 421,
                    Name: 'est'
                },
                {
                    id: 487,
                    Name: 'sed'
                },
                {
                    id: 203,
                    Name: 'quis'
                },
                {
                    id: 967,
                    Name: 'commodi'
                },
                {
                    id: 355,
                    Name: 'et'
                },
                {
                    id: 458,
                    Name: 'quisquam'
                },
                {
                    id: 336,
                    Name: 'quaerat'
                },
                {
                    id: 67,
                    Name: 'voluptates'
                },
                {
                    id: 262,
                    Name: 'architecto'
                },
                {
                    id: 289,
                    Name: 'error'
                },
                {
                    id: 337,
                    Name: 'explicabo'
                },
                {
                    id: 236,
                    Name: 'consequatur'
                },
                {
                    id: 302,
                    Name: 'consequatur'
                },
                {
                    id: 889,
                    Name: 'quod'
                },
                {
                    id: 486,
                    Name: 'tempore'
                },
                {
                    id: 63,
                    Name: 'fugit'
                },
                {
                    id: 7,
                    Name: 'corrupti'
                },
                {
                    id: 676,
                    Name: 'ut'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});