/*
 * File: app/store/Combo/CurrentlyLivesStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RiskManagement.store.Combo.CurrentlyLivesStore', {
    extend: 'Ext.data.Store',
    alias: 'store.currentlylivesmodels',

    requires: [
        'RiskManagement.model.CurrentlyLivesModel',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Combo.CurrentlyLivesStore',
            model: 'RiskManagement.model.CurrentlyLivesModel',
            data: [
                {
                    Id: 59,
                    Name: 'natus'
                },
                {
                    Id: 345,
                    Name: 'voluptate'
                },
                {
                    Id: 307,
                    Name: 'animi'
                },
                {
                    Id: 337,
                    Name: 'occaecati'
                },
                {
                    Id: 520,
                    Name: 'quae'
                },
                {
                    Id: 657,
                    Name: 'ratione'
                },
                {
                    Id: 458,
                    Name: 'placeat'
                },
                {
                    Id: 565,
                    Name: 'nemo'
                },
                {
                    Id: 118,
                    Name: 'delectus'
                },
                {
                    Id: 935,
                    Name: 'atque'
                },
                {
                    Id: 746,
                    Name: 'voluptatem'
                },
                {
                    Id: 750,
                    Name: 'quos'
                },
                {
                    Id: 410,
                    Name: 'omnis'
                },
                {
                    Id: 909,
                    Name: 'exercitationem'
                },
                {
                    Id: 932,
                    Name: 'id'
                },
                {
                    Id: 204,
                    Name: 'eius'
                },
                {
                    Id: 917,
                    Name: 'cupiditate'
                },
                {
                    Id: 599,
                    Name: 'porro'
                },
                {
                    Id: 225,
                    Name: 'placeat'
                },
                {
                    Id: 975,
                    Name: 'enim'
                },
                {
                    Id: 359,
                    Name: 'aut'
                },
                {
                    Id: 690,
                    Name: 'et'
                },
                {
                    Id: 199,
                    Name: 'omnis'
                },
                {
                    Id: 472,
                    Name: 'modi'
                },
                {
                    Id: 143,
                    Name: 'corporis'
                },
                {
                    Id: 653,
                    Name: 'nemo'
                },
                {
                    Id: 882,
                    Name: 'quia'
                },
                {
                    Id: 168,
                    Name: 'incidunt'
                },
                {
                    Id: 215,
                    Name: 'vel'
                },
                {
                    Id: 414,
                    Name: 'nihil'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});