/*
 * File: app/store/Combo/ISicCodeStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RiskManagement.store.Combo.ISicCodeStore', {
    extend: 'Ext.data.Store',
    alias: 'store.isiccodestore',

    requires: [
        'RiskManagement.model.Combo.IsicCodeModel',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Combo.ISicCodeStore',
            model: 'RiskManagement.model.Combo.IsicCodeModel',
            data: [
                {
                    id: 286,
                    Name: 'est'
                },
                {
                    id: 330,
                    Name: 'itaque'
                },
                {
                    id: 842,
                    Name: 'deserunt'
                },
                {
                    id: 948,
                    Name: 'recusandae'
                },
                {
                    id: 808,
                    Name: 'eius'
                },
                {
                    id: 398,
                    Name: 'corporis'
                },
                {
                    id: 204,
                    Name: 'officiis'
                },
                {
                    id: 879,
                    Name: 'aut'
                },
                {
                    id: 106,
                    Name: 'officia'
                },
                {
                    id: 766,
                    Name: 'eveniet'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});