/*
 * File: app/store/Combo/LocationIncomeStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RiskManagement.store.Combo.LocationIncomeStore', {
    extend: 'Ext.data.Store',
    alias: 'store.locationincomestore',

    requires: [
        'RiskManagement.model.Combo.LocationIncomeModel',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Combo.LocationIncomeStore',
            model: 'RiskManagement.model.Combo.LocationIncomeModel',
            data: [
                {
                    Id: 836,
                    Name: 'non'
                },
                {
                    Id: 287,
                    Name: 'autem'
                },
                {
                    Id: 613,
                    Name: 'velit'
                },
                {
                    Id: 594,
                    Name: 'consequuntur'
                },
                {
                    Id: 296,
                    Name: 'ut'
                },
                {
                    Id: 7,
                    Name: 'ut'
                },
                {
                    Id: 257,
                    Name: 'distinctio'
                },
                {
                    Id: 720,
                    Name: 'non'
                },
                {
                    Id: 540,
                    Name: 'aut'
                },
                {
                    Id: 477,
                    Name: 'iusto'
                },
                {
                    Id: 963,
                    Name: 'id'
                },
                {
                    Id: 111,
                    Name: 'dignissimos'
                },
                {
                    Id: 413,
                    Name: 'eum'
                },
                {
                    Id: 648,
                    Name: 'debitis'
                },
                {
                    Id: 317,
                    Name: 'qui'
                },
                {
                    Id: 711,
                    Name: 'ipsum'
                },
                {
                    Id: 342,
                    Name: 'deserunt'
                },
                {
                    Id: 342,
                    Name: 'velit'
                },
                {
                    Id: 994,
                    Name: 'ea'
                },
                {
                    Id: 488,
                    Name: 'repellat'
                },
                {
                    Id: 97,
                    Name: 'enim'
                },
                {
                    Id: 878,
                    Name: 'sunt'
                },
                {
                    Id: 93,
                    Name: 'voluptas'
                },
                {
                    Id: 532,
                    Name: 'quis'
                },
                {
                    Id: 66,
                    Name: 'quaerat'
                },
                {
                    Id: 139,
                    Name: 'sint'
                },
                {
                    Id: 854,
                    Name: 'sed'
                },
                {
                    Id: 885,
                    Name: 'ipsum'
                },
                {
                    Id: 586,
                    Name: 'hic'
                },
                {
                    Id: 54,
                    Name: 'dolore'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});