/*
 * File: app/store/Combo/OccupationTypeStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RiskManagement.store.Combo.OccupationTypeStore', {
    extend: 'Ext.data.Store',
    alias: 'store.occupationtypestore',

    requires: [
        'RiskManagement.model.Combo.OccupationTypeModel',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Combo.OccupationTypeStore',
            model: 'RiskManagement.model.Combo.OccupationTypeModel',
          //  autoLoad: true,
            proxy: {
                type: 'rest',
                url: 'api/common/GetOccupation?type=type',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});