/*
 * File: app/store/Combo/SourceOfIncomeStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RiskManagement.store.Combo.SourceOfIncomeStore', {
    extend: 'Ext.data.Store',
    alias: 'store.sourceofincomestore',

    requires: [
        'RiskManagement.model.Combo.SourceOfIncomeModel',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Combo.SourceOfIncomeStore',
            model: 'RiskManagement.model.Combo.SourceOfIncomeModel',
            data: [
                {
                    Id: 1,
                    Name: 'เงินสด'
                },
                {
                    Id: 2,
                    Name: 'ไม่ใช่เงินสด'
                }
            ],
            proxy: {
                type: 'memory'
            }
            //proxy: {
            //    type: 'rest',
            //    url: 'api/common/GetSourceOfIncome',
            //    reader: {
            //        type: 'json'
            //    }
            //}
        }, cfg)]);
    }
});