/*
 * File: app/store/Combo/SourceOfIncomeStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RiskManagement.store.Combo.SourceOfIncomeStore', {
    extend: 'Ext.data.Store',
    alias: 'store.sourceofincomestore',

    requires: [
        'RiskManagement.model.Combo.SourceOfIncomeModel',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Combo.SourceOfIncomeStore',
            model: 'RiskManagement.model.Combo.SourceOfIncomeModel',
            data: [
                {
                    id: 901,
                    Name: 'illo'
                },
                {
                    id: 559,
                    Name: 'id'
                },
                {
                    id: 505,
                    Name: 'eius'
                },
                {
                    id: 488,
                    Name: 'sit'
                },
                {
                    id: 444,
                    Name: 'repudiandae'
                },
                {
                    id: 277,
                    Name: 'aut'
                },
                {
                    id: 766,
                    Name: 'tenetur'
                },
                {
                    id: 684,
                    Name: 'consequatur'
                },
                {
                    id: 342,
                    Name: 'beatae'
                },
                {
                    id: 154,
                    Name: 'modi'
                },
                {
                    id: 75,
                    Name: 'ipsa'
                },
                {
                    id: 674,
                    Name: 'neque'
                },
                {
                    id: 990,
                    Name: 'quos'
                },
                {
                    id: 382,
                    Name: 'aperiam'
                },
                {
                    id: 322,
                    Name: 'numquam'
                },
                {
                    id: 249,
                    Name: 'rerum'
                },
                {
                    id: 182,
                    Name: 'eum'
                },
                {
                    id: 337,
                    Name: 'aut'
                },
                {
                    id: 321,
                    Name: 'quia'
                },
                {
                    id: 629,
                    Name: 'itaque'
                },
                {
                    id: 784,
                    Name: 'repellat'
                },
                {
                    id: 208,
                    Name: 'sed'
                },
                {
                    id: 729,
                    Name: 'veniam'
                },
                {
                    id: 873,
                    Name: 'quibusdam'
                },
                {
                    id: 595,
                    Name: 'quaerat'
                },
                {
                    id: 431,
                    Name: 'est'
                },
                {
                    id: 871,
                    Name: 'at'
                },
                {
                    id: 647,
                    Name: 'sit'
                },
                {
                    id: 571,
                    Name: 'iure'
                },
                {
                    id: 521,
                    Name: 'ipsa'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});