/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'LoginModel',
        'CorporationlModel',
        'ShareholdersModel',
        'Combo.OccupationCatelogyModel',
        'Combo.OccupationGroupModel',
        'Combo.OccupationTypeModel',
        'Combo.SourceOfIncomeModel',
        'Combo.BusinessTypeModel',
        'Combo.PositionModel',
        'Combo.LocationIncomeModel',
        'Combo.IsicCodeModel',
        'Combo.CommitteeTypeModel',
        'CurrentlyLivesModel',
        'TitleNameModel',
        'ShareholdersGridView',
        'Combo.RegionModel'
    ],
    stores: [
        'Combo.OccupationCatelogyStore',
        'Combo.OccupationGroupStore',
        'Combo.OccupationTypeStore',
        'Combo.SourceOfIncomeStore',
        'Combo.BusinessTypeStore',
        'Combo.PositionStore',
        'Combo.LocationIncomeStore',
        'Combo.ISicCodeStore',
        'Combo.CommitteeTypeStore',
        'Combo.CurrentlyLivesStore',
        'Combo.TitleNameStore',
        'Combo.RegionStore'
    ],
    views: [
        'MainView',
        'ShareholdersWindow',
        'PersonalForm',
        'CorporationlForm'
    ],
    name: 'RiskManagement',

    launch: function() {
        Ext.create('RiskManagement.view.MainView');
    }

});
