/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'LoginModel',
        'CorporationlModel',
        'ShareholdersModel',
        'Combo.OccupationCatelogyModel',
        'Combo.OccupationGroupModel',
        'Combo.OccupationTypeModel',
        'Combo.SourceOfIncomeModel',
        'Combo.BusinessTypeModel',
        'Combo.PositionModel',
        'Combo.LocationIncomeModel',
        'Combo.IsicCodeModel',
        'Combo.CommitteeTypeModel',
        'CurrentlyLivesModel',
        'TitleNameModel',
        'ShareholdersGridView',
        'Combo.RegionModel',
        'Combo.PoliticianRelationshipModel',
        'Combo.RegistrationTypeModel'
    ],
    stores: [
        'Combo.OccupationCatelogyStore',
        'Combo.OccupationGroupStore',
        'Combo.OccupationTypeStore',
        'Combo.SourceOfIncomeStore',
        'Combo.BusinessTypeStore',
        'Combo.PositionStore',
        'Combo.LocationIncomeStore',
        'Combo.ISicCodeStore',
        'Combo.CommitteeTypeStore',
        'Combo.CurrentlyLivesStore',
        'Combo.TitleNameStore',
        'Combo.RegionStore',
        'Combo.PoliticianRelationshipStore',
        'ShareholdersStore',
        'Combo.RegistrationTypeStore'
    ],
    views: [
        'MainView',
        'ShareholdersWindow',
        'PersonalForm',
        'CorporationlForm',
        'Admin.Main',
        'Admin.Tab.UploadFileViewModel'
    ],
    name: 'RiskManagement',

    launch: function () {
        // Ext.create('RiskManagement.view.MainView');
        console.log(window.Page);
        if (!window.Status && window.Page != "Admin" ) {

            Ext.Msg.alert('App not found', 'คุณไม่มีสิทธิใช้งานระบบนี้');
        }
        else if (window.Page === "Individual") {
            //if (true) {
            console.log("Individual");
            Ext.create('RiskManagement.view.PersonalForm', { renderTo: Ext.getBody() });

        } else if (window.Page === "Corporation") {

            Ext.create('RiskManagement.view.CorporationlForm', { renderTo: Ext.getBody() });
            console.log("Corporation");

        } else if (window.Page === "Admin") {
            Ext.create('RiskManagement.view.Admin.Main', { renderTo: Ext.getBody() });
            console.log("Admin");
        }
        
    }

});
