/*
 * File: app/view/CorporationlFormViewModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RiskManagement.view.CorporationlFormViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.corporationlform',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory'
    ],

    stores: {
        corporationlModels: {
            model: 'RiskManagement.model.CorporationlModel',
            data: [
                {
                    id: 674,
                    Individual: true,
                    Nationality: 'non',
                    RegistrationId: 153,
                    IsRegistrationThai: false,
                    RegistrationType: 861,
                    CompanyName: 'possimus',
                    OccupationCatelogy: 'dicta',
                    OccupationGroup: 'cupiditate',
                    OccupationType: 'sapiente',
                    Positon: 'vel',
                    BusinessType: 'animi',
                    SourceOfIncome: 'laborum',
                    LocationIncome: 'soluta',
                    LiveInCountry: 'itaque',
                    IsPolitician: false,
                    Tsic: 'impedit',
                    File1: 'qui',
                    File2: 'doloribus',
                    IsAccept: false
                },
                
            ],
            proxy: {
                type: 'memory'
            }
        },

        riskResultStoer: {
            model: 'RiskManagement.model.CorporationlModel',
            data: [
                {
                    id: 674,
                    Individual: true,
                    Nationality: 'non',
                    RegistrationId: 153,
                    IsRegistrationThai: false,
                    RegistrationType: 861,
                    CompanyName: 'possimus',
                    OccupationCatelogy: 'dicta',
                    OccupationGroup: 'cupiditate',
                    OccupationType: 'sapiente',
                    Positon: 'vel',
                    BusinessType: 'animi',
                    SourceOfIncome: 'laborum',
                    LocationIncome: 'soluta',
                    LiveInCountry: 'itaque',
                    IsPolitician: false,
                    Tsic: 'impedit',
                    File1: 'qui',
                    File2: 'doloribus',
                    IsAccept: false
                },

            ],
            proxy: {
                type: 'memory'
            }
        }
    }

});