/*
 * File: app/view/CorporationlForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RiskManagement.view.CorporationlForm', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.corporationlform',

    requires: [
        'RiskManagement.view.CorporationlFormViewModel',
        'RiskManagement.view.CorporationlFormViewController',
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.Checkbox',
        'Ext.form.field.ComboBox',
        'Ext.form.FieldContainer',
        'Ext.form.field.File',
        'Ext.button.Button'
    ],

    controller: 'corporationlform',
    viewModel: {
        type: 'corporationlform'
    },
    itemId: 'tab11',
    bodyPadding: 25,
    title: 'นิติบุคคล',

    items: [
        {
            xtype: 'form',
            reference: 'form',
            itemId: 'myform3',
            width: 750,
            defaults: {
                labelWidth: 175,
                labelAlign: 'right',
                margin: '5 5 5 5',
                afterLabelTextTpl: '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>',
                width: '95%',
                allowBlank: false
            },
            bodyPadding: 10,
            title: 'จัดการข้อมูลนิติบุคคล',
            layout: {
                type: 'table',
                columns: 2
            },
            items: [
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'ID',
                    name: 'id'
                },
                {
                    xtype: 'checkboxfield',
                    colspan: 2,
                    fieldLabel: 'นิติบุคคล',
                    name: 'Individual',
                    readOnly: true,
                    checked: true
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'สัญชาติ',
                    name: 'Nationality',
                    emptyText: '[ สัญชาติ ]',
                    displayField: 'Name',
                    store: 'Combo.RegionStore',
                    valueField: 'id'
                },
                {
                    xtype: 'checkboxfield',
                    fieldLabel: 'จดทะเบียนในประเทศไทย',
                    name: 'IsRegistrationThai'
                },
                {
                    xtype: 'textfield',
                    colspan: 2,
                    fieldLabel: 'เลขที่ทะเบียนการค้า',
                    name: 'RegistrationId',
                    emptyText: '[ xxxxxxxxxxxxx ]'
                },
                {
                    xtype: 'fieldcontainer',
                    colspan: 2,
                    width: '100%',
                    layout: 'table',
                    fieldLabel: 'บริษัท',
                    items: [
                        {
                            xtype: 'combobox',
                            margin: '0 5 0 0',
                            fieldLabel: 'จดทะเบียนบริษัท',
                            hideLabel: true,
                            name: 'RegistrationType',
                            allowBlank: false,
                            emptyText: '[ เลือกประเภทกิจการ ]',
                            displayField: 'Name',
                            store: 'Combo.ISicCodeStore',
                            valueField: 'id'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 5 0 0',
                            width: '100%',
                            fieldLabel: 'ชื่อบริษัท',
                            hideLabel: true,
                            name: 'CompanyName',
                            emptyText: '[ ชื่อบริษัท ]'
                        }
                    ]
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'หมวดอาชีพ',
                    name: 'OccupationCatelogy',
                    emptyText: '[ เลือกหมวดอาชีพ ]',
                    displayField: 'Name',
                    store: 'Combo.OccupationCatelogyStore',
                    valueField: 'Id'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'กลุ่มอาชีพ',
                    name: 'OccupationGroup',
                    emptyText: '[ เลือกกลุ่มอาชีพ ]',
                    displayField: 'Name',
                    store: 'Combo.OccupationGroupStore',
                    valueField: 'Id'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'ประเภทอาชีพ',
                    name: 'OccupationType',
                    emptyText: '[ เลือกประเภทอาชีพ ]',
                    displayField: 'Name',
                    store: 'Combo.OccupationTypeStore',
                    valueField: 'id'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'ตำแหน่ง',
                    name: 'Positon',
                    emptyText: '[ เลือกตำแหน่ง ]',
                    displayField: 'Name',
                    store: 'Combo.PositionStore',
                    valueField: 'Id'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'ประเภทธุรกิจ',
                    name: 'BusinessType',
                    emptyText: '[ เลือกประเภทอาชีพ ]',
                    displayField: 'Name',
                    store: 'Combo.BusinessTypeStore',
                    valueField: 'id'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'แหล่งที่มาของรายได้',
                    name: 'SourceOfIncome',
                    emptyText: '[ แหล่งที่มาของรายได้ ]',
                    displayField: 'Name',
                    store: 'Combo.SourceOfIncomeStore',
                    valueField: 'id'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'แหล่งที่ตั้งของรายได้',
                    name: 'LocationIncome',
                    emptyText: '[ เลือกที่ตั้งของรายได้ ]',
                    displayField: 'Name',
                    store: 'Combo.RegionStore',
                    valueField: 'id'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'อาศัยอยู่ที่ประเทศ',
                    name: 'LiveInCountry',
                    emptyText: '[ อาศัยอยู่ที่ประเทศ ]',
                    displayField: 'Name',
                    store: 'Combo.RegionStore',
                    valueField: 'id'
                },
                {
                    xtype: 'checkboxfield',
                    fieldLabel: 'ความสัมพันธ์กับนักการเมือง',
                    name: 'IsPolitician'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'ประเภทกิจการ',
                    name: 'Tsic',
                    emptyText: '[เลือกประเภทกิจการ ]',
                    displayField: 'Name',
                    store: 'Combo.ISicCodeStore',
                    valueField: 'id'
                },
                {
                    xtype: 'filefield',
                    colspan: 2,
                    width: '100%',
                    fieldLabel: 'หนังสือให้ความยินยอม ในการเปิดเผยข้อมูลบริษัท',
                    labelWidth: 300,
                    name: 'File1',
                    emptyText: 'ไฟล์'
                },
                {
                    xtype: 'filefield',
                    colspan: 2,
                    width: '100%',
                    fieldLabel: 'เอกสารแนบ KYC/CDD',
                    name: 'File2',
                    emptyText: 'ไฟล์'
                },
                {
                    xtype: 'checkboxfield',
                    colspan: 2,
                    fieldLabel: 'ความยินยอม ในการเปิดเผบข้อมูลบริษัท',
                    labelWidth: 250,
                    name: 'IsAccept'
                },
                {
                    xtype: 'container',
                    padding: 10,
                    layout: {
                        type: 'hbox',
                        align: 'middle',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            flex: 1,
                            formBind: true,
                            itemId: 'saveButton',
                            margin: 5,
                            text: 'Save',
                            listeners: {
                                click: 'onSave'
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            itemId: 'mybutton1',
                            text: 'กรรมการผู้ถือหุ้น',
                            tooltip: 'บันทึกกรรมการผู้ถือหุ้น',
                            listeners: {
                                click: 'onShareholdersClick'
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            itemId: 'cancelButton',
                            margin: 5,
                            text: 'Cancel',
                            listeners: {
                                click: 'onCancel'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});