/*
 * File: app/view/PersonalForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RiskManagement.view.PersonalForm', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.personalform',

    requires: [
        'RiskManagement.view.PersonalFormViewModel',
        'RiskManagement.view.PersonalFormViewController',
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.Checkbox',
        'Ext.form.field.Number',
        'Ext.form.FieldContainer',
        'Ext.form.field.ComboBox',
        'Ext.form.field.File',
        'Ext.button.Button'
    ],

    controller: 'personalform',
    viewModel: {
        type: 'personalform'
    },
    itemId: 'tab1',
    bodyPadding: 25,
    title: 'บุคคลธรรมดา',

    items: [
        {
            xtype: 'form',
            reference: 'form',
            itemId: 'myForm1',
            width: 750,
            defaults: {
                labelWidth: 175,
                labelAlign: 'right',
                margin: '5 5 5 5',
                afterLabelTextTpl: '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>',
                width: '95%'
            },
            bodyPadding: 10,
            title: 'บันทึกบุคคลธรรมดา',
            titleAlign: 'center',
            layout: {
                type: 'table',
                columns: 2
            },
            items: [
                {
                    xtype: 'hiddenfield',
                    width: 180,
                    fieldLabel: 'ID',
                    name: 'id'
                },
                {
                    xtype: 'checkboxfield',
                    colspan: 2,
                    fieldLabel: 'ประเภทบุคคล',
                    name: 'Individual',
                    checked: true
                },
                {
                    xtype: 'numberfield',
                    colspan: 2,
                    width: 338,
                    fieldLabel: 'เลขที่บัตรประชาชน',
                    name: 'IdCard',
                    allowBlank: false,
                    emptyText: ' 1234567890123',
                    maxLength: 13,
                    minLength: 13
                },
                {
                    xtype: 'fieldcontainer',
                    colspan: 2,
                    width: '100%',
                    layout: 'table',
                    fieldLabel: 'ชื่อ',
                    items: [
                        {
                            xtype: 'combobox',
                            margin: '0 5 0 0',
                            width: 93,
                            fieldLabel: 'คำนำหน้าชื่อ',
                            hideLabel: true,
                            name: 'TitleName',
                            allowBlank: false,
                            emptyText: '[ คำนำหน้า ]',
                            displayField: 'Name',
                            store: 'Combo.TitleNameStore',
                            valueField: 'Id'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 5 0 0',
                            fieldLabel: 'ชื่อจริง',
                            hideLabel: true,
                            name: 'FirstName',
                            allowBlank: false,
                            emptyText: '[ ชื่อจริง ]',
                            maxLength: 30,
                            minLength: 2
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 5 0 0',
                            fieldLabel: 'นามสกุล',
                            hideLabel: true,
                            name: 'LastName',
                            allowBlank: false,
                            emptyText: '[ นามสกุล ]',
                            maxLength: 30,
                            minLength: 2
                        }
                    ]
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'หมวดอาชีพ',
                    name: 'OccupationCatelogy',
                    emptyText: '[ เลือกหมวดอาชีพ ]',
                    displayField: 'Name',
                    store: 'Combo.OccupationCatelogyStore',
                    valueField: 'Id'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'กลุ่มอาชีพ',
                    name: 'OccupationGroup',
                    emptyText: '[ เลือกกลุ่มอาชีพ ]',
                    displayField: 'Name',
                    store: 'Combo.OccupationGroupStore',
                    valueField: 'Id'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'ประเภทอาชีพ',
                    name: 'OccupationType',
                    emptyText: '[ เลือกประเภทอาชีพ ]',
                    displayField: 'Name',
                    store: 'Combo.OccupationTypeStore',
                    valueField: 'id'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'ตำแหน่ง',
                    name: 'Position',
                    emptyText: '[ เลือกตำแหน่ง ]',
                    displayField: 'Name',
                    store: 'Combo.PositionStore',
                    valueField: 'Id'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'ประเภทธุรกิจ',
                    name: 'BusinessType',
                    emptyText: '[ เลือกประเภทธุรกิจ ]',
                    displayField: 'Name',
                    store: 'Combo.BusinessTypeStore',
                    valueField: 'id'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'แหล่งที่มาของรายได้',
                    name: 'SourceOfIncome',
                    emptyText: '[ แหล่งที่มาของรายได้ ]',
                    displayField: 'Name',
                    store: 'Combo.SourceOfIncomeStore',
                    valueField: 'id'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'อาศัยอยู่ในประเทศ',
                    name: 'LiveInCountry',
                    emptyText: '[ เลือกประเทศ ]',
                    displayField: 'Name',
                    store: 'Combo.RegionStore'
                },
                {
                    xtype: 'checkboxfield',
                    fieldLabel: 'ความสัมธ์กับนักการเมือง',
                    name: 'IsPolitician'
                },
                {
                    xtype: 'filefield',
                    colspan: 2,
                    fieldLabel: 'หนังสือความยินยอม ในการเปิดเผยข้อมูล',
                    labelWidth: 300,
                    name: 'File1',
                    emptyText: '[ File ]'
                },
                {
                    xtype: 'filefield',
                    colspan: 2,
                    fieldLabel: 'เอกสารแนบ KYC/CDD',
                    name: 'File2',
                    emptyText: '[ File ]'
                },
                {
                    xtype: 'checkboxfield',
                    colspan: 2,
                    fieldLabel: 'ความยินยอม',
                    name: 'IsAccept'
                },
                {
                    xtype: 'container',
                    colspan: 2,
                    padding: 10,
                    layout: {
                        type: 'hbox',
                        align: 'middle',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            flex: 1,
                            formBind: true,
                            itemId: 'saveButton',
                            margin: 5,
                            text: 'Save',
                            listeners: {
                                click: 'onSave'
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            itemId: 'cancelButton',
                            margin: 5,
                            text: 'Cancel',
                            listeners: {
                                click: 'onCancel'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});