/*
 * File: app/view/ShareholdersWindowViewModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RiskManagement.view.ShareholdersWindowViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.shareholderswindow',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory'
    ],

    stores: {
        shareholdersModels: {
            model: 'RiskManagement.model.ShareholdersModel',
            //data: [
            //    {
            //        id: 148,
            //        CorporationId: 3333333333333,
            //        CommitteeType: 1,
            //        IdCard: 3570,
            //        TitleName: 'qui',
            //        FirstName: 'et',
            //        LastName: 'omnis',
            //        OccupationCatelogy: {
            //            Id: 777,
            //            Name: 'est'
            //        },
            //        OccupationGroup: 1,
            //        OccupationType: 1,
            //        Position: 1,
            //        BusinessType: 1,
            //        SourceOfIncome: 1,
            //        LocationIncome: 1,
            //        CurrentlyLives: 1,
            //        IsPolitician: true,
            //        File1: 'eos',
            //        File2: 'aperiam',
            //        IsAccept: true
            //    },
            //    {
            //        id: 149,
            //        CorporationId: 3333333333333,
            //        CommitteeType: 2,
            //        IdCard: 3570,
            //        TitleName: 1,
            //        FirstName: 'e22t',
            //        LastName: 'o232mnis',
            //        OccupationCatelogy: {
            //            Id: 777,
            //            Name: 'est'
            //        },
            //        OccupationGroup: 1,
            //        OccupationType: 1,
            //        Position: 1,
            //        BusinessType: 1,
            //        SourceOfIncome: 1,
            //        LocationIncome: 1,
            //        CurrentlyLives: 1,
            //        IsPolitician: true,
            //        File1: 'eos',
            //        File2: 'aperiam',
            //        IsAccept: true
            //    }
            //],
            proxy: {
                type: 'memory'
            }
        },
        shareholdersGridViews: {
            pageSize: 10,
            model: 'RiskManagement.model.ShareholdersGridView',
            proxy: {
                type: 'rest',
                url: 'api/Shareholders/GetShareholdersGridView',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                },
                api: {
                    destroy: '/api/Shareholders'
                }
            }
        },
        shareholderForm: {
            model: 'RiskManagement.model.ShareholdersModel',
            autoLoad:true,
            proxy: {
                type: 'rest',
                url: 'api/Shareholders',
                reader: {
                    type: 'json'
                }
            }
        },

    }

});