/*
 * File: app/view/Admin/Tab/UploadFile.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RiskManagement.view.Admin.Tab.UploadFile', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tabuploadfile',

    requires: [
        'RiskManagement.view.Admin.Tab.UploadFileViewModel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.form.field.File',
        'Ext.button.Button',
        'Ext.grid.column.Number',
        'Ext.toolbar.Paging'
    ],

    viewModel: {
        type: 'uploadfile'
    },
    bodyPadding: 15,
    title: 'ตรวจสอบเอกสาร',

    items: [
        {
            xtype: 'gridpanel',
            title: 'My Grid Panel',
            bind: {
                store: '{mainUploads}'
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'filefield',
                            width: '30%',
                            fieldLabel: 'FileUpLoad'
                        },
                        {
                            xtype: 'button',
                            ui: 'default-small',
                            text: 'Loaddata'
                        }
                    ]
                },
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: '{mainUploads}'
                }
            ],
            columns: [
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'id',
                    text: 'ID'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'FileName',
                    text: 'File Name'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'Status',
                    text: 'Status'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'CurrentRecode',
                    text: 'Current Recode',
                    format: '00'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'Total',
                    text: 'Total',
                    format: '00'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'Active',
                    text: 'Active'
                }
            ]
        }
    ]

});