/*
 * File: app/view/Admin/Tab/UploadFileViewModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RiskManagement.view.Admin.Tab.UploadFileViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.uploadfile',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory'
    ],

    stores: {
        mainUploads: {
            model: 'RiskManagement.model.MainUploads',
            data: [
                {
                    id: 770,
                    FileName: 'aliquid',
                    Status: 691.19,
                    CurrentRecode: 558,
                    Total: 831,
                    Active: 466.44
                },
                {
                    id: 474,
                    FileName: 'quia',
                    Status: 164.91,
                    CurrentRecode: 476,
                    Total: 489,
                    Active: 104.6
                },
                {
                    id: 605,
                    FileName: 'eaque',
                    Status: 949.23,
                    CurrentRecode: 732,
                    Total: 74,
                    Active: 510.65
                },
                {
                    id: 299,
                    FileName: 'harum',
                    Status: 331.54,
                    CurrentRecode: 734,
                    Total: 556,
                    Active: 469.92
                },
                {
                    id: 830,
                    FileName: 'voluptatum',
                    Status: 77.32,
                    CurrentRecode: 926,
                    Total: 807,
                    Active: 975.93
                },
                {
                    id: 97,
                    FileName: 'aut',
                    Status: 315.31,
                    CurrentRecode: 874,
                    Total: 864,
                    Active: 479.18
                },
                {
                    id: 720,
                    FileName: 'et',
                    Status: 936.75,
                    CurrentRecode: 313,
                    Total: 343,
                    Active: 968.94
                },
                {
                    id: 545,
                    FileName: 'dolore',
                    Status: 149.75,
                    CurrentRecode: 414,
                    Total: 270,
                    Active: 784.72
                },
                {
                    id: 148,
                    FileName: 'enim',
                    Status: 449.72,
                    CurrentRecode: 390,
                    Total: 691,
                    Active: 573.37
                },
                {
                    id: 832,
                    FileName: 'nam',
                    Status: 484.6,
                    CurrentRecode: 414,
                    Total: 875,
                    Active: 990.88
                },
                {
                    id: 712,
                    FileName: 'est',
                    Status: 221.35,
                    CurrentRecode: 393,
                    Total: 746,
                    Active: 85.78
                },
                {
                    id: 748,
                    FileName: 'quas',
                    Status: 871.53,
                    CurrentRecode: 906,
                    Total: 531,
                    Active: 902.89
                },
                {
                    id: 733,
                    FileName: 'est',
                    Status: 961.76,
                    CurrentRecode: 792,
                    Total: 152,
                    Active: 730.16
                },
                {
                    id: 733,
                    FileName: 'aperiam',
                    Status: 772.65,
                    CurrentRecode: 975,
                    Total: 972,
                    Active: 933.53
                },
                {
                    id: 804,
                    FileName: 'consectetur',
                    Status: 38.15,
                    CurrentRecode: 130,
                    Total: 606,
                    Active: 848.42
                },
                {
                    id: 540,
                    FileName: 'id',
                    Status: 438.16,
                    CurrentRecode: 21,
                    Total: 543,
                    Active: 838.47
                },
                {
                    id: 869,
                    FileName: 'explicabo',
                    Status: 232.25,
                    CurrentRecode: 506,
                    Total: 932,
                    Active: 375.99
                },
                {
                    id: 380,
                    FileName: 'ad',
                    Status: 749.51,
                    CurrentRecode: 595,
                    Total: 389,
                    Active: 747.1
                },
                {
                    id: 642,
                    FileName: 'aut',
                    Status: 94.86,
                    CurrentRecode: 983,
                    Total: 844,
                    Active: 285.07
                },
                {
                    id: 589,
                    FileName: 'non',
                    Status: 251.04,
                    CurrentRecode: 139,
                    Total: 332,
                    Active: 232.2
                },
                {
                    id: 875,
                    FileName: 'rerum',
                    Status: 758.55,
                    CurrentRecode: 883,
                    Total: 585,
                    Active: 879.53
                },
                {
                    id: 172,
                    FileName: 'quam',
                    Status: 12.02,
                    CurrentRecode: 522,
                    Total: 405,
                    Active: 583.18
                },
                {
                    id: 757,
                    FileName: 'vitae',
                    Status: 726.2,
                    CurrentRecode: 732,
                    Total: 913,
                    Active: 338.12
                },
                {
                    id: 358,
                    FileName: 'asperiores',
                    Status: 726.25,
                    CurrentRecode: 613,
                    Total: 19,
                    Active: 494.61
                },
                {
                    id: 351,
                    FileName: 'ex',
                    Status: 570.12,
                    CurrentRecode: 70,
                    Total: 921,
                    Active: 744.77
                }
            ],
            proxy: {
                type: 'memory'
            }
        }
    }

});